---
name: consul
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  serial: false
  update_watch_time: 5000-1200000
instance_groups: []

releases:
- name: consul
  version: 23.0.4

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

