---
name: consul
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  serial: false
  update_watch_time: 5000-1200000
  max_in_flight: 50

releases:
- name: consul
  version: 23.0.4

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: consul
  azs: [z1]
  instances: 3
  vm_type: default
  networks:
  - name: default
  stemcell: default
  jobs:
  - name: consul
    release: consul
