---
resources:
- name: consul-deployment
  type: bosh-deployment
  source:
    ca_cert: {{director-ca-cert}}
    target: {{director-address}}
    client: {{director-client}}
    client_secret: {{director-client-secret}}
    deployment: {{deployment}}
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: {{ stemcell }}
- name: release
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/consul-boshrelease
- name: bosh-deploy-pipeline
  type: git
  source:
    uri: "https://github.com/hkumarmk/concourse-pipelines.git"
    paths: [consul/*]

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

jobs:
- name: deploy
  plan:
  - aggregate:
    - get: release
    - get: stemcell
    - get: bosh-deploy-pipeline
  - put: consul-deployment
    params:
      manifest: bosh-deploy-pipeline/consul/deployment.yml
      vars_files:
      - bosh-deploy-pipeline/consul/example-vars.yml
      releases:
      - release/*.tgz
      stemcells:
      - stemcell/*.tgz
