name: haproxy

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: haproxy
  version: latest
